console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'
  
  [[blocks.segments]]
  type = 'executiontime'
  style = 'plain'
  foreground = 'yellow'
  background = 'transparent'
  template = '{{ div .Ms 1000}}s '
  
  [blocks.segments.properties]
    threshold = 1000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true
  
  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'blue'
    
    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'gray'
    background = 'transparent'
    template = '{{ .HEAD }}{{if or (.Working.Changed) (.Staging.Changed) }}* {{ end }} '
    
    [blocks.segments.properties]
    branch_icon = ''
    fetch_status = true
    
  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      '{{if gt .Code 0}}red{{end}}',
      '{{if eq .Code 0}}magenta{{end}}'
    ]
    background = 'transparent'
    template = '〉'
    
[transient_prompt]
  foreground_templates = [
      '{{if gt .Code 0}}red{{end}}',
      '{{if eq .Code 0}}magenta{{end}}'
  ]
  background = 'transparent'
  template = '〉'
